%% Initialization script
clear
% Setting the text interpreter in plots as latex...
set(groot,'defaulttextinterpreter','latex');  
set(groot, 'defaultAxesTickLabelInterpreter','latex');  
set(groot, 'defaultLegendInterpreter','latex');

dyn_params                  % initializing the plant...
% INS_init                    % initializing the onboard sensors...
% EKF2_init                   % initializing the filter...

open trajPlann_init.m       % opening trajectory planner creator...
open simPlots.m             % opening plotting script...


